file_list = [
    "https://www.youtube.com/watch?v=8-KalRPhCxc",
    "https://www.youtube.com/watch?v=dG9lRLXtaec",
    "https://www.youtube.com/watch?v=OTkp2FbSWjg&t=1801s",
    "https://www.youtube.com/watch?v=Y2WzoVExNrU",
    "https://www.youtube.com/watch?v=KHN36y5a4uQ&t=1377s",
    "https://www.youtube.com/watch?v=XwX-CWy7_x4",
    "https://www.youtube.com/watch?v=gS6TmF6pGCw",
    "https://www.youtube.com/watch?v=2z5eX7AkkjQ&t=737s",
    "https://www.youtube.com/watch?v=R5k_TIJ-yyg",
    "https://www.youtube.com/watch?v=7ZRvXIiF4eg&t=857s",
    "https://www.youtube.com/watch?v=-dIeRe5zCNE",
    "https://www.youtube.com/watch?v=RQAPUEHcIro",
    "https://www.youtube.com/watch?v=udB022VKw3s&t=704s",
    "https://www.youtube.com/watch?v=enl-n315_X4",
    "https://www.youtube.com/watch?v=lPmgK8gr-vk",
    "https://www.youtube.com/watch?v=vPMigZx6vZI&t=1709s",
    "https://www.youtube.com/watch?v=dvnXG3CdP1I",
    "https://www.youtube.com/watch?v=-hn7xyOYz7s",
    "https://www.youtube.com/watch?v=AEHNusfS2Bo",
    "https://www.youtube.com/watch?v=XCBAepfNNA4&t=2161s",
    "https://www.youtube.com/watch?v=x_fbXUaCOdk",
    "https://www.youtube.com/watch?v=_4iom6TZ4S0",
    "https://www.youtube.com/watch?v=bHn91coO5T4",
    "https://www.youtube.com/watch?v=ta3F75x_3x8",
    "https://www.youtube.com/watch?v=6R6B-OV3680",
    "https://www.youtube.com/watch?v=iVQr1jBfsOQ",
    "https://www.youtube.com/watch?v=TOq_lYtuEWo",
    "https://www.youtube.com/watch?v=1GQjNtBM5bs",
    "https://www.youtube.com/watch?v=PYhbPV7MahE",
    "https://www.youtube.com/watch?v=r4Xstoq18gA",
    "https://www.youtube.com/watch?v=_v1CD-VJdc0",
    "https://www.youtube.com/watch?v=0_aiqllOtQM",
    "https://www.youtube.com/watch?v=BSBXgnjgJE4",
    "https://www.youtube.com/watch?v=aOBjmXDBFik",
    "https://www.youtube.com/watch?v=cGBO0bt7Vj0",
    "https://www.youtube.com/watch?v=5VWuWuZegWI",
    "https://www.youtube.com/watch?v=WnMQOTANkh4",
    "https://www.youtube.com/watch?v=iMJ1xxnekbU",
    "https://www.youtube.com/watch?v=_Nfp7SB0IBA",
    "https://www.youtube.com/watch?v=4VyFMTYIz1Q",
    "https://www.youtube.com/watch?v=a8poqolNZ6k",
    "https://www.youtube.com/watch?v=b4_q2dJub-E&t=1197s",
    "https://www.youtube.com/watch?v=m04-ows2eng",
    "https://www.youtube.com/watch?v=0zpVSx9LHao",
    "https://www.youtube.com/watch?v=nHDU-sHzDRE",
    "https://www.youtube.com/watch?v=9vaLkYElidg",
    "https://www.youtube.com/watch?v=NvfrkbNwIjQ",
    "https://www.youtube.com/watch?v=KHN36y5a4uQ",
    "https://www.youtube.com/watch?v=kU_oR9QPom8&t=914s",
    "https://www.youtube.com/watch?v=3DHhUyhWMco&t=1360s",
    "https://www.youtube.com/watch?v=uRgBZ-YuSik&t=1658s",
    "https://www.youtube.com/watch?v=ZvZF9_cZdQo&t=2635s",
    "https://www.youtube.com/watch?v=DoO7H5SW5oA",
    "https://www.youtube.com/watch?v=AbecYUe0iVY&t=1083s",
    "https://www.youtube.com/watch?v=m04-ows2eng",
    "https://www.youtube.com/watch?v=6XGGuCVtiRo",
    "https://www.youtube.com/watch?v=Ms9PbzMp8uk",
    "https://www.youtube.com/watch?v=EuCchmgoxlo",
    "https://www.youtube.com/watch?v=U0PhQcdfJHw",
    "https://www.youtube.com/watch?v=_0BKXxIyXm0",
    "https://www.youtube.com/watch?v=ZpPW3oleY4A&t=2778s",
    "https://www.youtube.com/watch?v=rHKCWKZA6RI",
    "https://www.youtube.com/watch?v=RTT2PZuqOSA",
    "https://www.youtube.com/watch?v=4df0KtYHWwo",
    "https://www.youtube.com/watch?v=yJFTFdgH5Bc",
    "https://www.youtube.com/watch?v=LlbmvZu2zuk",
    "https://www.youtube.com/watch?v=Dcpe_tgFoXg",
    "https://www.youtube.com/watch?v=7SHNyXtkSP8",
    "https://www.youtube.com/watch?v=DmhFljZXsg4",
    "https://www.youtube.com/watch?v=6qdzX31q2Nk",
    "https://www.youtube.com/watch?v=PHB7QrmmHFA",
    "https://www.youtube.com/watch?v=M9voXLBcKTk",
    "https://www.youtube.com/watch?v=v4BNhlFl7KY",
    "https://www.youtube.com/watch?v=Pih15rO4ncY",
    "https://www.youtube.com/watch?v=FuVTGA0FOvk",
    "https://www.youtube.com/watch?v=o4mxr0DnIQE",
    "https://www.youtube.com/watch?v=NIeAvhNTBTU",
    "https://www.youtube.com/watch?v=lL-s5tpuqzY",
    "https://www.youtube.com/watch?v=ZQZ5NQuHOCc",
    "https://www.youtube.com/watch?v=DjBB0dGsaDg",
    "https://www.youtube.com/watch?v=oJd3NRQa-C8",
    "https://www.youtube.com/watch?v=JtHCqPv58TY",
    "https://www.youtube.com/watch?v=5IbjzOMn2ws",
    "https://www.youtube.com/watch?v=OhX33ifUhkM",
    "https://www.youtube.com/watch?v=5asc4hN4F94",
    "https://www.youtube.com/watch?v=Bn3NewE2Cww",
    "https://www.youtube.com/watch?v=YhBb5sPw8IA",
    "https://www.youtube.com/watch?v=bAAYZbnGm4M",
    "https://www.youtube.com/watch?v=gvQQ9BePQrw",
    "https://www.youtube.com/watch?v=GZ3AJjDdEcc",
    "https://www.youtube.com/watch?v=zi_Np9BfXgM",
    "https://www.youtube.com/watch?v=C9sGDFV7TbQ",
    "https://www.youtube.com/watch?v=mhgD08eOqgE",
    "https://www.youtube.com/watch?v=4DypzubMrBg",
    "https://www.youtube.com/watch?v=prj0jFoG6TU",
    "https://www.youtube.com/watch?v=-RcLjB9uMHM",
    "https://www.youtube.com/watch?v=BymjPkXqrqg",
    "https://www.youtube.com/watch?v=6iFrQKg5Cjo",
    "https://www.youtube.com/watch?v=-nRrw0i162k",
    "https://www.youtube.com/watch?v=0sEXUI8qFow",
]


from multiprocessing import Pool
import os
import subprocess

SAVE_FOLDER = "/home/thanh/zalocl2022/data/youtube"

def download(url):
    video_id = url.split("watch?v=")[1].split("&")[0]
    if video_id + ".wav" in os.listdir(SAVE_FOLDER):
        return

    subprocess.run(f'youtube-dl -x --audio-format wav -o "{SAVE_FOLDER}/%(id)s.%(ext)s" {url}', shell=True)

if __name__ == '__main__':
    with Pool(32) as p:
        print(p.map(download, file_list))